name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["PyPi and Docker Deploy"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' 

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rhinosecuritylabs/pacu:latest
      
    - name: Docker Push
      run: docker push rhinosecuritylabs/pacu:latest
